name: CI

on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    container:
      image: docker:stable
    steps:
      - name: Echo env variables
        run: |
          docker ps -a
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

